name: DropChest
main: com.narrowtux.DropChest.DropChest
version: 0.6.9
author: narrowtux
description: DropChest sucks dropped loot into Chests. It's very useful if you do automatic farming or have mobs traps which gather the loot.
commands:
 dropchest:
  description: Access to all DropChest related commands
  aliases:
      - dc
 item:
  description: Gives you the name or the id of the passed item.
  usage: /item [NAME|id]