name: DropChest
main: com.narrowtux.DropChest.DropChest
version: 0.8.3
author: narrowtux
description: DropChest sucks dropped loot into Chests. It's very useful if you do automatic farming or have mobs traps which gather the loot.
commands:
 dropchest:
  description: Access to all DropChest related commands
  aliases:
      - dc
 dcitem:
  description: Gives you the name or the id of the passed item.
  usage: /dcitem [NAME|id]
 chestinfo:
  description: Gives you information about a chests contents. Omit the argument and rightclick on a non-dropchest
  usage: /chestinfo {name|id}
permissions:
 dropchest:
  description: basic permission to gain usage of this plugin.
  default: true
 dropchest.create:
  default: true
 dropchest.remove:
  default: true
 dropchest.radius.set:
  default: true
 dropchest.radius.setBig:
  default: op
 dropchest.which:
  default: true
 dropchest.teleport:
  default: op
 dropchest.filter:
  default: true
 dropchest.filter:
  default: true
 dropchest.filter.set:
  default: true
 dropchest.filter.reset:
  default: true
 dropchest.list:
  default: true
 dropchest.destroy:
  default: false
 dropchest.protect:
  default: true
 dropchest.moderator:
  default: op